### ISSUE TITLE
s3_to_github 同步失败

### ISSUE THREAD

**Issue by kadidala** [fscarmen2/pic-hosting-cluster#1]
# 首先向大佬致敬！感谢提供这么好的工具！
根据大佬的视频把 r2 升级到了 s3, 也把s3_to_github和config都改好了，但是上传了测试图片后，运行同步action就报错。用r2_to_github同步却是正常的。
我的s3_to_github配置如下：

```
name: S3 --> GitHub

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  S3_To_GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Sync files to GitHub
        uses: fscarmen2/r2_to_github@v1.0.1
```
报错如下：
```
Run fscarmen2/r2_to_github@v1.0.1
Run # 脚本开始，输出起始日志
开始 Storage ---> GitHub 脚本
/home/runner/work/_temp/a0167[4](https://github.com/kadidala/file-sync/actions/runs/12214497532/job/34075334991#step:3:5)3f-770b-41e0-bb97-24354129ebd9.sh: line 113: [: : integer expression expected
克隆节点 
Cloning into 'kadidala'...
remote: Repository not found.
fatal: repository 'https://github.com/kadidala/.git/' not found
Error: Process completed with exit code 128.
```
我是有创建三个github私库的，分别为node-1 node-2 node-3.

**Comment by fscarmen2** [comment]
把config.yml文件，内容改些值，但一定要保留现在的格式，发来看看。估计这时有值不标准导致出问题了。

**Comment by kadidala** [comment]
大佬，这是我的config.yml，格式没动，就秘钥相关数值删减了
```
# 以下所有的 KV 填写格式要求: 1. 修改的地方需要把尖括号一并去掉；2. : 冒号后面有空格
## GitHub 部分
github_pat: github_pat_11AV5MMGY0ImYS5SH4CJyw_cHo0Uf9IK6QblfZaejNdDOrUPKjQL3TB6X636hbP1RCF
github_repo_prefix: node-

## GitLab 部分
gitlab_repo_prefix: node-
gitlab_username: didala
gitlab_pats:
  # 注意，下面只填仓库名数字序号，比如 repo1,repo2,repo3,repo4，就只填 1,2,3,4 即可
  1: glpat-9mat-yoTzv4U5G
  2: glpat-P4x_dNFkPZzc
  3: glpat-ZyihF6yguKQp

## CloudFlare R2 部分
r2_accounts:
  - name: kad
    account_id: c225264ba415dc9759e808
    access_key_id: 0370ef209a3c8f91b3aef532
    secret_access_key: c439d4b9e6fb4152ae06c9a71dc67720c0fad96cabdb7e74106
    bucket: r2-1
    dir: files
  - name: kad3
    account_id: 13eefd1a21794385740c5
    access_key_id: 1fb7524064271c0dbd2148f58a
    secret_access_key: af745ae77edd41395f8f02ba0b93d1cb7f49e483a
    bucket: r2-2
    dir: files
  - name: kadll4
    account_id: a36456a891ed4feb4be3d
    access_key_id: 582949c8b90e181a5e5293ea8
    secret_access_key: 36ad74862fb89deb1379279902b38def631bfaa2e731ce69236
    bucket: r2-3
    dir: files
      
## Backblaze B2 部分
    
## Backblaze B2 部分
b2_accounts:
  - name: kadil
    endpoint: s3.usckblazeb2.com
    key_id: 004fa0fe79db0000001
    application_key: K004z2irErid+Hb5nQ
    bucket: bb2-node-1
    dir: files
  - name: kadidkk
    endpoint: s3.us-wckblazeb2.com
    key_id: 00473add00000002
    application_key: K004gHX2fs8W5c5TE
    bucket: bb2-node-2
    dir: files
  - name: kadiii
    endpoint: s3.us-westzeb2.com
    key_id: 004b8cfe9a7b0000001
    application_key: K004hJqeLwbU2d+EmD4wY
    bucket: bb2-node-3
    dir: files
## 备份策略
strategy: size    # 可选 [size (默认) | quantity | 指定节点]; size: 选择容量最少的仓库来存储文件; quantity: 选择文件最少的仓库来存储文件; 指定节点: 比如  pic1 或者 pic2
delete: true    # 可选 [true (默认) | false]，已复制到 GitHub 的文件，是否从 R2 删除

```
