### ISSUE TITLE
r2->github 失败

### ISSUE THREAD

**Issue by ink100** [fscarmen2/pic-hosting-cluster#2]
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
开始 R2 ---> GitHub 脚本
Error: Cannot get keys of !!null, keys only works for maps and arrays

配置文件没改动，仅仅删除 gitlab部分
以下是目录截图和 action的报错
<img width="614" alt="企业微信截图_17339721436064" src="https://github.com/user-attachments/assets/76c42046-3a8c-4407-83d2-48d159da210d" />
<img width="673" alt="企业微信截图_17339722762586" src="https://github.com/user-attachments/assets/b812c786-7d55-47dc-820d-d65023ece3cf" />

**Comment by fscarmen** [comment]
回头看看，测试时没试过这样

**Comment by ink100** [comment]
> 回头看看，测试时没试过这样

我只部署了r2-github，其中 r2 有文件(r2 含有多个文件夹)， github 仓库没有文件， ，大佬有空可以看看哈，L站也问你了

**Comment by fscarmen2** [comment]
你按 #1 那位一样，改为敏感密码，保留完整格式，发个 config.yml ，今晚我看看

你个多目录的话，只处理你指定目录下的文件的

你gh库的名分别是什么？

**Comment by ink100** [comment]
> 你按 #1 那位一样，改为敏感密码，保留完整格式，发个 config.yml ，今晚我看看
> 
> 你个多目录的话，只处理你指定目录下的文件的
> 
> 你gh库的名分别是什么？

1.gh任务库是[syncFile]
2.gh存储库为storage-x  x为数字
3，config的配置如下
```YML
# 以下所有的 KV 填写格式要求: 1. 修改的地方需要把尖括号一并去掉；2. : 冒号后面有空格
## GitHub 部分
github_pat: github_pat_后缀已删除
github_repo_prefix: storage-1,storage-2,storage-3,storage-4,storage-5
## GitLab 部分
## CloudFlare R2 部分
r2_accounts:
  - name: ink100
    account_id: c587a1893012348845b9dcd21234
    access_key_id: aedbafe112349eca555accd1234
    secret_access_key: aba35e27220a12346a3538b5c8e1234
    bucket: storage-r2-1
    dir: files


## 备份策略
strategy: size    # 可选 [size (默认) | quantity | 指定节点]; size: 选择容量最少的仓库来存储文件; quantity: 选择文件最少的仓库来存储文件; 指定节点: 比如  pic1 或者 pic2
delete: true    # 可选 [true (默认) | false]，已复制到 GitHub 的文件，是否从 R2 删除
```

**Comment by fscarmen2** [comment]
你试下先，gh你有多少个序号，在gl那里就填几个，现以4个为例，那些值为a的保留
```
# 以下所有的 KV 填写格式要求: 1. 修改的地方需要把尖括号一并去掉；2. : 冒号后面有空格

## GitLab 部分
gitlab_repo_prefix: storage-
gitlab_username: a
gitlab_pats:
  # 注意，下面只填仓库名数字序号，比如 repo1,repo2,repo3,repo4，就只填 1,2,3,4 即可
  1: a
  2: a
  3: a
  4: a

## GitHub 部分
github_pat: github_pat_后缀已删除
github_repo_prefix: storage-

## CloudFlare R2 部分
r2_accounts:
  - name: ink100
    account_id: c587a1893012348845b9dcd21234
    access_key_id: aedbafe112349eca555accd1234
    secret_access_key: aba35e27220a12346a3538b5c8e1234
    bucket: storage-r2-1
    dir: files

## 备份策略
strategy: size    # 可选 [size (默认) | quantity | 指定节点]; size: 选择容量最少的仓库来存储文件; quantity: 选择文件最少的仓库来存储文件; 指定节点: 比如  pic1 或者 pic2
delete: true    # 可选 [true (默认) | false]，已复制到 GitHub 的文件，是否从 R2 删除
```
